# Generated by Django 3.2 on 2021-04-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='categories',
            field=models.ManyToManyField(to='books.Category'),
        ),
    ]
