# Generated by Django 3.2 on 2021-04-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20210422_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='isbn',
            name='desc',
            field=models.CharField(default='def description', max_length=30),
        ),
    ]
