# Generated by Django 3.2 on 2021-04-22 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_isbn_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='isbn',
            old_name='desc',
            new_name='description',
        ),
    ]
