# Generated by Django 3.2 on 2021-04-22 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_rename_desc_isbn_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isbn',
            name='created_at',
        ),
    ]
